#!/usr/bin/env python3
"""Run the complete analyze-first agent-ready-this assessment pipeline."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

GENERATOR = "agent-ready-this@0.2.0-plan"


def run_stage(command: list[str]) -> None:
    try:
        subprocess.run(command, check=True)
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"Assessment stage failed with exit code {exc.returncode}: {' '.join(command)}") from exc


def active_group(item: dict[str, Any]) -> str:
    applicability = item.get("applicability")
    priority = item.get("priority")
    if applicability == "blocked":
        return "blocked"
    if applicability in {"conditional", "report-only"}:
        return "conditional"
    if applicability == "not-applicable":
        return "not-applicable"
    if applicability in {"required", "recommended"} and priority in {"P0", "P1"}:
        return "do-now"
    return "do-next"


def render_question(question: dict[str, Any]) -> list[str]:
    lines = [
        f"### {question['id']} — {question['topic']} [{question['severity']}]",
        "",
        f"**Finding:** {question['finding']}",
    ]
    evidence = question.get("evidence", [])
    if evidence:
        lines.append(f"**Evidence:** {', '.join(f'`{item}`' for item in evidence[:8])}")
    lines.extend(
        [
            f"**Why this changes the plan:** {question['why_it_matters']}",
            f"**Current recommendation:** {question['current_recommendation']}",
            f"**Question:** {question['question']}",
            "",
        ]
    )
    options = question.get("options", [])
    if options:
        lines.append("Options:")
        for option in options:
            consequence = f" — {option.get('consequence')}" if option.get("consequence") else ""
            lines.append(f"- **{option['id']}** — {option['label']}{consequence}")
        lines.append("")
    lines.extend(
        [
            f"**Safe default if unanswered:** {question['safe_default']}",
            f"**Affects:** {', '.join(f'`{item}`' for item in question.get('affects', [])) or 'assessment scope'}",
            "",
        ]
    )
    return lines


def render_report(audit: dict[str, Any], recs: dict[str, Any], grill: dict[str, Any]) -> str:
    repository = audit.get("repository", {})
    signals = audit.get("signals", {})
    inventory = audit.get("inventory", {})
    quality = signals.get("quality_commands", {})
    groups: dict[str, list[dict[str, Any]]] = {
        "do-now": [],
        "do-next": [],
        "conditional": [],
        "blocked": [],
        "not-applicable": [],
    }
    for item in recs.get("recommendations", []):
        groups[active_group(item)].append(item)

    lines: list[str] = [
        "# Agent Ready This — Preliminary Assessment",
        "",
        f"Generated by `{GENERATOR}`.",
        "",
        "## Project snapshot",
        "",
        f"- **Repository:** `{repository.get('path', '')}`",
        f"- **Files scanned:** {repository.get('file_count_scanned', 0)}" + (" (truncated)" if repository.get("scan_truncated") else ""),
        f"- **Languages:** {', '.join(signals.get('languages', [])) or 'not established'}",
        f"- **Frameworks:** {', '.join(signals.get('frameworks', [])) or 'not established'}",
        f"- **Package managers:** {', '.join(signals.get('package_managers', [])) or 'not established'}",
        f"- **Monorepo evidence:** {', '.join(signals.get('monorepo_evidence', [])) or 'none detected'}",
        f"- **Core quality gates found:** {quality.get('core_coverage', 0)}/{quality.get('core_total', 4)}",
        f"- **CI detected:** {'yes' if signals.get('ci_candidate') else 'no'}",
        f"- **Existing agent clients:** {', '.join(signals.get('vendor_clients_detected', [])) or 'none detected'}",
        "",
        "## Evidence-backed recommendations",
        "",
    ]

    headings = [
        ("do-now", "Do now"),
        ("do-next", "Do next"),
        ("conditional", "Conditional / plan-only"),
        ("blocked", "Blocked"),
        ("not-applicable", "Do not add now"),
    ]
    for key, heading in headings:
        items = groups[key]
        lines.extend([f"### {heading}", ""])
        if not items:
            lines.extend(["_None._", ""])
            continue
        for item in items:
            evidence = item.get("evidence", [])
            evidence_text = f" Evidence: {', '.join(f'`{value}`' for value in evidence[:5])}." if evidence else ""
            unknown_text = ""
            if item.get("unknowns"):
                unknown_text = " Unknown: " + " ".join(item["unknowns"])
            lines.append(
                f"- **{item['priority']} · {item['title']}** — `{item['applicability']}` / `{item['action']}`. "
                f"{item['reason']}{evidence_text}{unknown_text}"
            )
        lines.append("")

    gate = grill.get("gate", {})
    lines.extend(
        [
            "## Grill Gate",
            "",
            f"- **Status:** `{gate.get('status', 'skipped')}`",
            f"- **Depth:** `{gate.get('depth', 'none')}`",
            f"- **Materiality score:** {gate.get('materiality_score', 0)}",
            f"- **Safe baseline work can proceed:** {'yes' if gate.get('safe_work_can_proceed') else 'no'}",
        ]
    )
    for reason in gate.get("reasons", []):
        lines.append(f"- {reason}")
    lines.append("")

    first_round_ids = set(grill.get("next_round", []))
    first_round = [q for q in grill.get("questions", []) if q.get("id") in first_round_ids]
    if first_round:
        lines.extend(["## Grill Session — Round 1", ""])
        for question in first_round:
            lines.extend(render_question(question))
        lines.append("Reply in prose or with compact IDs such as `G-12: ...`.")
        lines.append("")
    else:
        lines.extend(
            [
                "## Grill Session",
                "",
                "Questions were not presented; unresolved decisions remain in grill-session.json."
                if grill.get("questions")
                else "Skipped because no unanswered material decision remains at the configured threshold.",
                "",
            ]
        )

    safe_ids = recs.get("summary", {}).get("safe_to_proceed", [])
    lines.extend(["## Safe next action", ""])
    if safe_ids:
        lines.append(
            "The following baseline recommendations can be planned independently of unresolved runtime questions: "
            + ", ".join(f"`{item}`" for item in safe_ids)
            + "."
        )
    else:
        lines.append("Resolve the first blocking Grill round before finalizing the affected plan.")
    lines.extend(
        [
            "",
            "## Assessment limitations",
            "",
            "- This pass is heuristic and read-only with respect to project source files.",
            "- High-impact commands, authorization behavior, and public interfaces still require direct verification and execution.",
            "- Preliminary recommendations must be recomputed after material Grill answers.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".")
    parser.add_argument("--output-dir", required=True, help="New directory for assessment artifacts; existing directories are rejected.")
    parser.add_argument("--known-context")
    parser.add_argument("--public-web", action="store_true")
    parser.add_argument("--authenticated-ui-actions", action="store_true")
    parser.add_argument("--headless-actions", action="store_true")
    parser.add_argument("--visual-tool-results", action="store_true")
    parser.add_argument("--agent-service", action="store_true")
    parser.add_argument("--public-discovery", action="store_true")
    parser.add_argument("--sensitive-actions", action="store_true")
    parser.add_argument("--target-vendor", action="append", default=[])
    parser.add_argument("--experimental", choices=["off", "report-only", "allow"], default="report-only")
    parser.add_argument("--grill-mode", choices=["auto", "off", "force"], default="auto")
    parser.add_argument("--grill-threshold", choices=["conservative", "balanced", "aggressive"], default="balanced")
    parser.add_argument("--max-grill-total", type=int, default=15)
    parser.add_argument("--max-grill-per-round", type=int, default=1)
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    repo = Path(args.repo).resolve()
    if not repo.is_dir():
        raise SystemExit(f"Repository path is not a directory: {repo}")
    output_dir = Path(args.output_dir).resolve()
    skill_root = script_dir.parent
    if output_dir == skill_root or skill_root in output_dir.parents:
        raise SystemExit("Assessment output must be outside the installed skill.")
    try:
        output_dir.mkdir(parents=True, exist_ok=False)
    except OSError as exc:
        raise SystemExit(f"Cannot create a new assessment directory: {output_dir}: {exc}") from exc

    audit_path = output_dir / "audit.json"
    recommendations_path = output_dir / "recommendations.preliminary.json"
    grill_path = output_dir / "grill-session.json"
    report_path = output_dir / "assessment.md"

    run_stage(
        [
            sys.executable,
            str(script_dir / "inspect_repo.py"),
            "--repo",
            str(repo),
            "--output",
            str(audit_path),
        ]
    )

    decide_command = [
        sys.executable,
        str(script_dir / "decide_integrations.py"),
        "--audit",
        str(audit_path),
        "--output",
        str(recommendations_path),
        "--experimental",
        args.experimental,
    ]
    for flag, enabled in (
        ("--public-web", args.public_web),
        ("--authenticated-ui-actions", args.authenticated_ui_actions),
        ("--headless-actions", args.headless_actions),
        ("--visual-tool-results", args.visual_tool_results),
        ("--agent-service", args.agent_service),
        ("--public-discovery", args.public_discovery),
        ("--sensitive-actions", args.sensitive_actions),
    ):
        if enabled:
            decide_command.append(flag)
    for vendor in args.target_vendor:
        decide_command.extend(["--target-vendor", vendor])
    run_stage(decide_command)

    grill_command = [
        sys.executable,
        str(script_dir / "build_grill_session.py"),
        "--audit",
        str(audit_path),
        "--recommendations",
        str(recommendations_path),
        "--output",
        str(grill_path),
        "--mode",
        args.grill_mode,
        "--threshold",
        args.grill_threshold,
        "--max-total",
        str(args.max_grill_total),
        "--max-per-round",
        str(args.max_grill_per_round),
    ]
    if args.known_context:
        grill_command.extend(["--known-context", args.known_context])
    run_stage(grill_command)

    audit = json.loads(audit_path.read_text(encoding="utf-8"))
    recommendations = json.loads(recommendations_path.read_text(encoding="utf-8"))
    grill = json.loads(grill_path.read_text(encoding="utf-8"))
    report_path.write_text(render_report(audit, recommendations, grill), encoding="utf-8")

    result = {
        "audit": str(audit_path),
        "recommendations": str(recommendations_path),
        "grill_session": str(grill_path),
        "report": str(report_path),
        "grill_status": grill.get("gate", {}).get("status"),
    }
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
