#!/usr/bin/env python3
"""Build an adaptive Grill Session from preliminary agent-ready-this recommendations."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

GENERATOR = "agent-ready-this@0.3.0-plan"

QUESTION_SPECS: dict[str, dict[str, Any]] = {
    "quality_commands": {
        "id": "G-01",
        "category": "commands-and-validation",
        # A heuristic command gap is resolved from CI, README, and task runners first; it is not a user blocker.
        "severity": "major",
        "materiality": 8,
        "question": "Which install, build, lint, typecheck, and test commands are authoritative when the repository does not expose a complete verified set?",
        "why_it_matters": "Agents cannot safely claim completion or CI parity when the quality contract is ambiguous.",
        "current_recommendation": "Standardize explicit project/package scripts and make CI call the same commands.",
        "safe_default": "Do not invent commands. Mark the missing gates blocked and document only commands that can be executed successfully.",
        "options": [
            {"id": "A", "label": "Standardize package-level scripts", "consequence": "Portable and easy for agents and CI to discover."},
            {"id": "B", "label": "Use an existing task runner as canonical", "consequence": "Good for monorepos if its scopes and prerequisites are documented."},
            {"id": "C", "label": "Keep current commands and document exceptions", "consequence": "Lowest change, but may preserve inconsistency."},
        ],
    },
    "package_scope_ownership": {
        "id": "G-02",
        "category": "commands-and-ownership",
        "severity": "major",
        "materiality": 6,
        "question": "Which packages or subtrees have distinct owners, commands, or architectural rules that justify nested instructions?",
        "why_it_matters": "This determines where nested AGENTS.md files belong and prevents root instructions from becoming inaccurate.",
        "current_recommendation": "Create nested instructions only for genuinely divergent scopes and keep them delta-only.",
        "safe_default": "Keep one root AGENTS.md and defer nested files until divergence is proven.",
        "options": [],
    },
    "ownership_conflicts": {
        "id": "G-03",
        "category": "managed-files",
        "severity": "major",
        "materiality": 7,
        "question": "Which existing instruction files are human-owned, and which may be managed or generated by agent-ready-this?",
        "why_it_matters": "The answer controls whether the plan proposes patches, managed blocks, or generated files and avoids clobbering established rules.",
        "current_recommendation": "Treat every existing file as human-owned until explicit ownership metadata says otherwise.",
        "safe_default": "Generate proposed patches only; do not overwrite or adopt existing files.",
        "options": [
            {"id": "A", "label": "All existing files remain human-owned", "consequence": "Safest; updates are patch proposals."},
            {"id": "B", "label": "Allow managed blocks in selected files", "consequence": "Enables refresh while preserving manual sections."},
            {"id": "C", "label": "Generate selected files completely", "consequence": "Requires explicit file list and hash-based conflict protection."},
        ],
    },
    "critical_workflows": {
        "id": "G-04",
        "category": "product-and-workflow",
        "severity": "minor",
        "materiality": 4,
        "question": "Which two or three repeated project workflows currently consume the most agent time or fail most often?",
        "why_it_matters": "Dedicated Agent Skills should target high-value repeated procedures rather than create a large unused skill catalog.",
        "current_recommendation": "Start with quality gates plus one domain workflow such as release, migration, asset processing, or feature implementation.",
        "safe_default": "Document verified commands in existing guidance; add a skill only for an evidenced repeated procedure.",
        "options": [],
    },
    "target_agents": {
        "id": "G-05",
        "category": "target-clients",
        "severity": "minor",
        "materiality": 4,
        "question": "Which coding-agent clients require first-class support in the first release?",
        "why_it_matters": "This determines which thin vendor adapters are worth maintaining and which should be omitted.",
        "current_recommendation": "Keep AGENTS.md and .agents/skills canonical, then add adapters only for actively used clients.",
        "safe_default": "Ship the portable canonical layer without vendor adapters.",
        "options": [
            {"id": "A", "label": "Portable canonical layer only", "consequence": "Lowest maintenance and broad fallback compatibility."},
            {"id": "B", "label": "Canonical layer plus detected clients", "consequence": "Balanced default for existing workflows."},
            {"id": "C", "label": "Explicit first-class client list", "consequence": "Best native experience but requires ongoing adapter maintenance."},
        ],
    },
    "public_scope": {
        "id": "G-06",
        "category": "public-exposure",
        "severity": "major",
        "materiality": 7,
        "question": "Which base URL and documentation/content paths are intentionally public and safe to reference from llms.txt?",
        "why_it_matters": "Publishing the wrong paths can expose internal material, stale routes, or authenticated content.",
        "current_recommendation": "Index only stable public documentation and product pages; never treat llms.txt as access control.",
        "safe_default": "Do not publish llms.txt until the public surface is explicitly enumerated.",
        "options": [],
    },
    "api_contract_scope": {
        "id": "G-07",
        "category": "contracts",
        "severity": "major",
        "materiality": 6,
        "question": "Which HTTP routes are stable, supported interfaces rather than private implementation details?",
        "why_it_matters": "This determines whether OpenAPI documents a real contract or accidentally freezes internal routes.",
        "current_recommendation": "Start with a narrow supported API surface and generate schemas from implementation where possible.",
        "safe_default": "Keep OpenAPI plan-only and document candidate routes without publishing a contract.",
        "options": [],
    },
    "api_workflows": {
        "id": "G-08",
        "category": "contracts",
        "severity": "minor",
        "materiality": 4,
        "question": "Which multi-step API workflows are stable and important enough to deserve executable Arazzo documentation?",
        "why_it_matters": "Arazzo adds value for consequential sequences, not simple CRUD or unstable flows.",
        "current_recommendation": "Add it only for a small set of high-value workflows after OpenAPI is validated.",
        "safe_default": "Skip Arazzo in the first release.",
        "options": [],
    },
    "event_contract_scope": {
        "id": "G-09",
        "category": "contracts",
        "severity": "major",
        "materiality": 6,
        "question": "Which events or channels are stable contracts consumed outside their implementation module?",
        "why_it_matters": "AsyncAPI should describe durable integration boundaries, not every internal queue or transient event.",
        "current_recommendation": "Document only externally consumed or cross-service channels with versioned payloads.",
        "safe_default": "Keep AsyncAPI plan-only until consumers and compatibility guarantees are known.",
        "options": [],
    },
    "page_vs_headless": {
        "id": "G-10",
        "category": "runtime-boundary",
        "severity": "major",
        "materiality": 7,
        "question": "Must the proposed agent actions work when the user does not have the application page open?",
        "why_it_matters": "A page-bound answer favors WebMCP; a page-independent answer favors MCP or an existing API. Choosing incorrectly duplicates interfaces.",
        "current_recommendation": "Use WebMCP only for actions inseparable from the current page/session; use headless interfaces for reusable domain actions.",
        "safe_default": "Do not add WebMCP; preserve the human UI and keep runtime access plan-only.",
        "options": [
            {"id": "A", "label": "Only inside the open signed-in page", "consequence": "WebMCP may fit with feature detection and fallback."},
            {"id": "B", "label": "Must work without the page", "consequence": "Prefer MCP or an existing authenticated API."},
            {"id": "C", "label": "Both", "consequence": "Requires one shared domain-action layer and two thin adapters."},
        ],
    },
    "runtime_consumers": {
        "id": "G-11",
        "category": "runtime-boundary",
        "severity": "major",
        "materiality": 7,
        "question": "Who will call the agent-facing runtime interface, from which environment, and on whose authority?",
        "why_it_matters": "Caller identity determines transport, authentication, scopes, rate limits, audit records, and whether runtime exposure is needed at all.",
        "current_recommendation": "Name concrete caller classes before selecting a runtime protocol.",
        "safe_default": "Restrict the first release to local development-agent use and expose no remote runtime interface.",
        "options": [
            {"id": "A", "label": "Local coding agents", "consequence": "Local transport and repository permissions may be sufficient."},
            {"id": "B", "label": "Hosted agents acting for signed-in users", "consequence": "Requires remote auth, resource scopes, and auditing."},
            {"id": "C", "label": "Other autonomous services/agents", "consequence": "Requires service identity, delegation, and lifecycle contracts."},
        ],
    },
    "authz_model": {
        "id": "G-12",
        "category": "security",
        "severity": "blocking",
        "materiality": 10,
        "question": "What is the authoritative resource-level authorization model for agent actions: user, organization, project, asset, environment, or another unit?",
        "why_it_matters": "Authentication alone does not prove that a caller may read or mutate a specific resource. Runtime tools are unsafe without this boundary.",
        "current_recommendation": "Call the same server-side authorization layer used by the product and test cross-tenant denial explicitly.",
        "safe_default": "Block runtime mutation and remote private-data access; allow only documented public or local read-only operations.",
        "options": [],
    },
    "mutation_policy": {
        "id": "G-13",
        "category": "security",
        "severity": "blocking",
        "materiality": 10,
        "question": "Which actions may mutate data or cause external effects, and which require preview, explicit confirmation, idempotency keys, or two-step commit?",
        "why_it_matters": "Retries and ambiguous intent can duplicate, delete, publish, charge, message, or overwrite data.",
        "current_recommendation": "Separate read/write tools, make consequential writes idempotent, and require explicit confirmation for destructive or external effects.",
        "safe_default": "Expose no mutating runtime tools; keep them plan-only until the policy is explicit and tested.",
        "options": [],
    },
    "transport_deployment": {
        "id": "G-14",
        "category": "deployment",
        "severity": "major",
        "materiality": 7,
        "question": "Should the runtime interface be local stdio, remote authenticated HTTP, or both?",
        "why_it_matters": "Transport changes the trust boundary, deployment model, secret handling, observability, and compatibility work.",
        "current_recommendation": "Begin local when the capability is developer-only; choose remote only for a concrete hosted caller.",
        "safe_default": "Local read-only transport or no runtime server in the first phase.",
        "options": [
            {"id": "A", "label": "Local stdio", "consequence": "Simpler trust boundary; tied to local project access."},
            {"id": "B", "label": "Remote authenticated HTTP", "consequence": "Supports hosted callers but requires production-grade auth and operations."},
            {"id": "C", "label": "Both through shared domain actions", "consequence": "Maximum reach with higher testing and maintenance cost."},
        ],
    },
    "experimental_fallback": {
        "id": "G-15",
        "category": "experimental-capabilities",
        "severity": "blocking",
        "materiality": 8,
        "question": "What maintained fallback remains when an experimental agent surface is unavailable or changes?",
        "why_it_matters": "An experimental protocol cannot be a single point of failure for core user or agent workflows.",
        "current_recommendation": "Keep existing UI/API behavior canonical and treat the experimental layer as a feature-detected adapter.",
        "safe_default": "Report the capability only; do not implement it in the critical path.",
        "options": [],
    },
    "visual_tool_need": {
        "id": "G-16",
        "category": "runtime-ui",
        "severity": "minor",
        "materiality": 4,
        "question": "Which MCP result specifically requires an interactive map, table, editor, preview, or approval surface rather than structured text?",
        "why_it_matters": "MCP Apps add packaging and host-compatibility cost and should solve a concrete visual task.",
        "current_recommendation": "Add a UI only for one proven high-value tool and preserve a structured fallback.",
        "safe_default": "Return structured data without an embedded app.",
        "options": [],
    },
    "agent_task_lifecycle": {
        "id": "G-17",
        "category": "agent-interoperability",
        "severity": "blocking",
        "materiality": 9,
        "question": "What delegated task lifecycle must the agent service support, including progress, cancellation, retry, timeout, and artifact delivery?",
        "why_it_matters": "Without a real task lifecycle, A2A would misrepresent a normal API or tool collection as an autonomous agent.",
        "current_recommendation": "Define a small state machine and test cancellation and artifact semantics before publishing an Agent Card.",
        "safe_default": "Do not publish A2A metadata; expose the underlying API or MCP tools instead if appropriate.",
        "options": [],
    },
    "discovery_scope": {
        "id": "G-18",
        "category": "public-exposure",
        "severity": "major",
        "materiality": 6,
        "question": "Which agentic resources are intentionally public, stable, and maintained strongly enough to appear in a discovery catalog?",
        "why_it_matters": "A catalog creates a public compatibility and trust commitment across multiple resources.",
        "current_recommendation": "Publish only versioned resources with owners, health expectations, and verified URLs.",
        "safe_default": "Skip public discovery and document resources privately until the publication contract is clear.",
        "options": [],
    },
    "success_criteria": {
        "id": "G-19",
        "category": "rollout",
        "severity": "minor",
        "materiality": 4,
        "question": "What measurable outcome must improve for this project to be considered agent-ready?",
        "why_it_matters": "A concrete acceptance target prevents the effort from becoming a file-creation checklist.",
        "current_recommendation": "Use task success rate, clean setup, correct scoped checks, and reduced agent correction loops as primary measures.",
        "safe_default": "Use the applicable existing project checks and report untested agent behavior; choose evals only for an observed risk.",
        "options": [],
    },
}

SEVERITY_ORDER = {"blocking": 0, "major": 1, "minor": 2}


def load_known_context(path: str | None) -> tuple[set[str], list[dict[str, Any]]]:
    if not path:
        return set(), []
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    known = set(str(item) for item in data.get("known_topics", []))
    answers = list(data.get("answers", []))
    topics_by_id = {spec["id"]: topic for topic, spec in QUESTION_SPECS.items()}
    for answer in answers:
        topic = topics_by_id.get(answer.get("question_id"))
        value = answer.get("value")
        settled = (
            answer.get("status") == "answered"
            and answer.get("source") in {
                "repository-evidence", "explicit-user-answer",
                "prior-user-context", "inferred-from-evidence",
            }
            and value not in (None, "", [], {})
            and (not isinstance(value, str) or bool(value.strip()))
        )
        if topic and settled:
            known.add(topic)
    return known, answers


def build_finding(recs: list[dict[str, Any]]) -> str:
    unknowns: list[str] = []
    for item in recs:
        unknowns.extend(str(value) for value in item.get("unknowns", []) if value)
    if unknowns:
        return " ".join(dict.fromkeys(unknowns))
    reasons = [str(item.get("reason", "")) for item in recs if item.get("reason")]
    return " ".join(dict.fromkeys(reasons)) or "A material decision remains unresolved after repository inspection."


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audit", required=True)
    parser.add_argument("--recommendations", required=True)
    parser.add_argument("--output")
    parser.add_argument("--known-context")
    parser.add_argument("--mode", choices=["auto", "off", "force"], default="auto")
    parser.add_argument("--threshold", choices=["conservative", "balanced", "aggressive"], default="balanced")
    parser.add_argument("--max-total", type=int, default=15)
    parser.add_argument("--max-per-round", type=int, default=1)
    args = parser.parse_args()

    if not 1 <= args.max_per_round <= 5:
        raise SystemExit("--max-per-round must be between 1 and 5")
    if not 1 <= args.max_total <= 30:
        raise SystemExit("--max-total must be between 1 and 30")

    audit_path = Path(args.audit)
    recommendations_path = Path(args.recommendations)
    audit = json.loads(audit_path.read_text(encoding="utf-8"))
    rec_doc = json.loads(recommendations_path.read_text(encoding="utf-8"))
    recommendations = list(rec_doc.get("recommendations", []))
    known_topics, known_answers = load_known_context(args.known_context)

    topic_to_recs: dict[str, list[dict[str, Any]]] = {}
    for recommendation in recommendations:
        if recommendation.get("applicability") in {"not-applicable"}:
            continue
        for topic in recommendation.get("grill_topics", []):
            topic_to_recs.setdefault(str(topic), []).append(recommendation)

    suppressed_topics = sorted(topic for topic in topic_to_recs if topic in known_topics)
    active_topics = [topic for topic in topic_to_recs if topic not in known_topics]

    if args.mode == "force" and not active_topics:
        active_topics = ["critical_workflows", "success_criteria"]
        topic_to_recs.setdefault("critical_workflows", [])
        topic_to_recs.setdefault("success_criteria", [])

    minimum_materiality = {"conservative": 8, "balanced": 6, "aggressive": 4}[args.threshold]
    candidates: list[dict[str, Any]] = []
    for topic in active_topics:
        spec = QUESTION_SPECS.get(topic)
        if not spec:
            continue
        if spec["severity"] != "blocking" and spec["materiality"] < minimum_materiality:
            continue
        affected_recs = topic_to_recs.get(topic, [])
        evidence: list[str] = []
        for recommendation in affected_recs:
            evidence.extend(str(item) for item in recommendation.get("evidence", []) if item)
        item = {
            "id": spec["id"],
            "round": 1,
            "topic": topic,
            "category": spec["category"],
            "severity": spec["severity"],
            "materiality": spec["materiality"],
            "finding": build_finding(affected_recs),
            "evidence": list(dict.fromkeys(evidence))[:20],
            "question": spec["question"],
            "why_it_matters": spec["why_it_matters"],
            "current_recommendation": spec["current_recommendation"],
            "options": spec["options"],
            "safe_default": spec["safe_default"],
            "affects": sorted({str(rec.get("id")) for rec in affected_recs if rec.get("id")}),
            "status": "pending",
        }
        candidates.append(item)

    candidates.sort(
        key=lambda item: (
            SEVERITY_ORDER[item["severity"]],
            -int(item["materiality"]),
            -len(item["affects"]),
            item["id"],
        )
    )
    questions = candidates[: args.max_total]
    for index, question in enumerate(questions):
        question["round"] = index // args.max_per_round + 1

    if any(question["severity"] == "blocking" for question in questions):
        gate_status = "required"
        gate_reasons = [
            "At least one unresolved decision affects security, runtime exposure, authoritative commands, or irreversible architecture."
        ]
    elif questions:
        gate_status = "useful"
        gate_reasons = [
            "Material answers would improve prioritization or product fit, while safe baseline work can proceed independently."
        ]
    else:
        gate_status = "skipped"
        gate_reasons = [
            "No unresolved question passed the materiality threshold after evidence and known-context suppression."
        ]

    blocking_ids = [question["id"] for question in questions if question["severity"] == "blocking"]
    if not questions:
        depth = "none"
    elif len(questions) <= 4 and len(blocking_ids) <= 1:
        depth = "light"
    elif len(questions) <= 8 and len(blocking_ids) <= 2:
        depth = "standard"
    else:
        depth = "deep"

    materiality_score = sum(int(question["materiality"]) for question in questions)
    safe_work = bool(rec_doc.get("summary", {}).get("safe_to_proceed", []))
    next_round = [question["id"] for question in questions if question["round"] == 1]
    if args.mode == "off":
        next_round = []
        gate_reasons.append("Question presentation was disabled; unresolved decisions remain in the report.")

    result = {
        "schema_version": 1,
        "generator": GENERATOR,
        "source_audit": str(audit_path),
        "source_recommendations": str(recommendations_path),
        "gate": {
            "status": gate_status,
            "depth": depth,
            "materiality_score": materiality_score,
            "reasons": gate_reasons,
            "blocking_question_ids": blocking_ids,
            "safe_work_can_proceed": safe_work,
        },
        "questions": questions,
        "answers": known_answers,
        "suppressed_topics": suppressed_topics,
        "next_round": next_round,
    }

    text = json.dumps(result, indent=2, ensure_ascii=False) + "\n"
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
